name: harry_potter_app
description: A new Flutter project.

publish_to: 'none' # Bu proje pub.dev'de yayınlanmayacak

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ses oynatmak için audioplayers paketi
  audioplayers: ^6.5.0

  # UI & Animasyonlar
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  google_fonts: ^6.1.0

  # API & Durum Yönetimi
  dio: ^5.4.3
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

  # Model Oluşturma
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Kod üretimi (Freezed / JSON)
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/alive.json
    - assets/lottie/dead.json
    - assets/sounds/harry_potter.mp3
